encoding: utf-8
source: src/
destination: dist/
title: Ellipsis Guide
email: info@ellipsis.ai
description: How to use Ellipsis.ai
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ellipsis.ai" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: EllipsisBot
github_username:  ellipsis-ai
repository: "ellipsis-ai/ellipsis-ai.github.io"

collections:
  developer_reference:
    output: true
    permalink: /developers/reference/:path/
    title: Developer’s reference
  developer_cookbook:
    output: true
    permalink: /developers/cookbook/:path/
    title: Developer’s cookbook

defaults:
  - scope:
      path: ""
      type: developer_reference
    values:
      layout: developers
  - scope:
      path: ""
      type: developer_cookbook
    values:
      layout: developers
