theme: jekyll-theme-minimal


source: src/
destination: dist/

title: Ellipsis Guide
email: info@ellipsis.ai
description: > # this means to ignore newlines until "baseurl:"
How to use Ellipsis.ai
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ellipsis.ai" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: EllipsisBot
github_username:  ellipsis-ai
repository: "ellipsis-ai/ellipsis-ai.github.io"
