#!/bin/bash

if [ -z "${AWS_PROFILE}" ]
then
  echo "You need to set AWS_PROFILE"
  exit 1
fi

aws configure set preview.cloudfront true

aws s3 sync ./_site s3://docs.ellipsis.ai/ --acl=public-read

aws cloudfront create-invalidation \
    --paths /index.html /index.json /404.html \
    --distribution-id E32EYVF68FB1JG
