#!/bin/bash

if [ -z "${AWS_PROFILE}" ]
then
  echo "You need to set AWS_PROFILE"
  exit 1
fi

aws configure set preview.cloudfront true
aws s3 sync ./dist s3://docs.ellipsis.ai/ --acl=public-read --delete
aws cloudfront create-invalidation \
       --paths /index.html /assets/*  /developers/* \
       --distribution-id E18Q2N6CZFALZW
